export const COUNTRIES_MOCK = [
  {
    name: {
      common: 'Bangladesh',
      official: "People's Republic of Bangladesh",
      nativeName: {
        ben: { official: 'বাংলাদেশ গণপ্রজাতন্ত্রী', common: 'বাংলাদেশ' },
      },
    },
    tld: ['.bd'],
    cca2: 'BD',
    ccn3: '050',
    cca3: 'BGD',
    cioc: 'BAN',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { BDT: { name: 'Bangladeshi taka', symbol: '৳' } },
    idd: { root: '+8', suffixes: ['80'] },
    capital: ['Dhaka'],
    altSpellings: [
      'BD',
      "People's Republic of Bangladesh",
      'Gônôprôjatôntri Bangladesh',
    ],
    region: 'Asia',
    subregion: 'Southern Asia',
    languages: { ben: 'Bengali' },
    translations: {
      ara: { official: 'جمهورية بنغلاديش الشعبية', common: 'بنغلاديش' },
      bre: { official: 'Republik pobl Bangladesh', common: 'Bangladesh' },
      ces: { official: 'Bangladéšská lidová republika', common: 'Bangladéš' },
      cym: { official: 'Gweriniaeth Pobl Bangladesh', common: 'Bangladesh' },
      deu: { official: 'Volksrepublik Bangladesch', common: 'Bangladesch' },
      est: { official: 'Bangladeshi Rahvavabariik', common: 'Bangladesh' },
      fin: { official: 'Bangladeshin kansantasavalta', common: 'Bangladesh' },
      fra: {
        official: 'La République populaire du Bangladesh',
        common: 'Bangladesh',
      },
      hrv: { official: 'Narodna Republika Bangladeš', common: 'Bangladeš' },
      hun: { official: 'Banglades', common: 'Banglades' },
      ita: {
        official: 'Repubblica popolare del Bangladesh',
        common: 'Bangladesh',
      },
      jpn: { official: 'バングラデシュ人民共和国', common: 'バングラデシュ' },
      kor: { official: '방글라데시 인민 공화국', common: '방글라데시' },
      nld: { official: 'Volksrepubliek Bangladesh', common: 'Bangladesh' },
      per: { official: 'جمهوری خلق بنگلادش', common: 'بنگلادش' },
      pol: { official: 'Ludowa Republika Bangladeszu', common: 'Bangladesz' },
      por: {
        official: 'República Popular do Bangladesh',
        common: 'Bangladesh',
      },
      rus: { official: 'Народная Республика Бангладеш', common: 'Бангладеш' },
      slk: { official: 'Bangladéšska ľudová republika', common: 'Bangladéš' },
      spa: {
        official: 'República Popular de Bangladesh',
        common: 'Bangladesh',
      },
      srp: { official: 'Народна Република Бангладеш', common: 'Бангладеш' },
      swe: { official: 'Folkrepubliken Bangladesh', common: 'Bangladesh' },
      tur: { official: 'Bangladeş Halk Cumhuriyeti', common: 'Bangladeş' },
      urd: { official: 'عوامی جمہوریہ بنگلہ دیش', common: 'بنگلہ دیش' },
      zho: { official: '孟加拉人民共和国', common: '孟加拉国' },
    },
    latlng: [24.0, 90.0],
    landlocked: false,
    borders: ['MMR', 'IND'],
    area: 147570.0,
    demonyms: {
      eng: { f: 'Bangladeshi', m: 'Bangladeshi' },
      fra: { f: 'Bangladaise', m: 'Bangladais' },
    },
    flag: '\uD83C\uDDE7\uD83C\uDDE9',
    maps: {
      googleMaps: 'https://goo.gl/maps/op6gmLbHcvv6rLhH6',
      openStreetMaps: 'https://www.openstreetmap.org/relation/184640',
    },
    population: 164689383,
    gini: { '2016': 32.4 },
    fifa: 'BAN',
    car: { signs: ['BD'], side: 'left' },
    timezones: ['UTC+06:00'],
    continents: ['Asia'],
    flags: {
      png: 'https://flagcdn.com/w320/bd.png',
      svg: 'https://flagcdn.com/bd.svg',
      alt: 'The flag of Bangladesh has a dark green field bearing a large red circle that is offset slightly towards the hoist side of center.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/bd.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/bd.svg',
    },
    startOfWeek: 'sunday',
    capitalInfo: { latlng: [23.72, 90.4] },
    postalCode: { format: '####', regex: '^(\\d{4})$' },
  },
  {
    name: {
      common: 'Pakistan',
      official: 'Islamic Republic of Pakistan',
      nativeName: {
        eng: { official: 'Islamic Republic of Pakistan', common: 'Pakistan' },
        urd: { official: 'اسلامی جمہوریۂ پاكستان', common: 'پاكستان' },
      },
    },
    tld: ['.pk'],
    cca2: 'PK',
    ccn3: '586',
    cca3: 'PAK',
    cioc: 'PAK',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { PKR: { name: 'Pakistani rupee', symbol: '₨' } },
    idd: { root: '+9', suffixes: ['2'] },
    capital: ['Islamabad'],
    altSpellings: [
      'PK',
      'Pākistān',
      'Islamic Republic of Pakistan',
      "Islāmī Jumhūriya'eh Pākistān",
    ],
    region: 'Asia',
    subregion: 'Southern Asia',
    languages: { eng: 'English', urd: 'Urdu' },
    translations: {
      ara: { official: 'جمهورية باكستان الإسلامية', common: 'باكستان' },
      bre: { official: 'Republik islamek Pakistan', common: 'Pakistan' },
      ces: { official: 'Pákistánská islámská republika', common: 'Pákistán' },
      cym: { official: 'Islamic Republic of Pakistan', common: 'Pakistan' },
      deu: { official: 'Islamische Republik Pakistan', common: 'Pakistan' },
      est: { official: 'Pakistani Islamivabariik', common: 'Pakistan' },
      fin: {
        official: 'Pakistanin islamilainen tasavalta',
        common: 'Pakistan',
      },
      fra: { official: 'République islamique du Pakistan', common: 'Pakistan' },
      hrv: { official: 'Islamska Republika Pakistan', common: 'Pakistan' },
      hun: { official: 'Pakisztán', common: 'Pakisztán' },
      ita: { official: 'Repubblica islamica del Pakistan', common: 'Pakistan' },
      jpn: { official: 'パキスタン', common: 'パキスタン' },
      kor: { official: '파키스탄 이슬람 공화국', common: '파키스탄' },
      nld: { official: 'Islamitische Republiek Pakistan', common: 'Pakistan' },
      per: { official: 'جمهوری اسلامی پاکستان', common: 'پاکستان' },
      pol: { official: 'Islamska Republika Pakistanu', common: 'Pakistan' },
      por: { official: 'República Islâmica do Paquistão', common: 'Paquistão' },
      rus: { official: 'Исламская Республика Пакистан', common: 'Пакистан' },
      slk: { official: 'Pakistanská islamská republika', common: 'Pakistan' },
      spa: { official: 'República Islámica de Pakistán', common: 'Pakistán' },
      srp: { official: 'Исламска Република Пакистан', common: 'Пакистан' },
      swe: { official: 'Islamiska republiken Pakistan', common: 'Pakistan' },
      tur: { official: 'Pakistan İslam Cumhuriyeti', common: 'Pakistan' },
      urd: { official: 'اسلامی جمہوریہ پاکستان', common: 'پاکستان' },
      zho: { official: '巴基斯坦伊斯兰共和国', common: '巴基斯坦' },
    },
    latlng: [30.0, 70.0],
    landlocked: false,
    borders: ['AFG', 'CHN', 'IND', 'IRN'],
    area: 881912.0,
    demonyms: {
      eng: { f: 'Pakistani', m: 'Pakistani' },
      fra: { f: 'Pakistanaise', m: 'Pakistanais' },
    },
    flag: '\uD83C\uDDF5\uD83C\uDDF0',
    maps: {
      googleMaps: 'https://goo.gl/maps/5LYujdfR5yLUXoERA',
      openStreetMaps: 'https://www.openstreetmap.org/relation/307573',
    },
    population: 220892331,
    gini: { '2018': 31.6 },
    fifa: 'PAK',
    car: { signs: ['PK'], side: 'left' },
    timezones: ['UTC+05:00'],
    continents: ['Asia'],
    flags: {
      png: 'https://flagcdn.com/w320/pk.png',
      svg: 'https://flagcdn.com/pk.svg',
      alt: 'The flag of Pakistan is composed of a white vertical band on its hoist side that takes up about one-fourth the width of the field and a dark green rectangular area that spans the rest of the field. A white fly-side facing crescent and five-pointed star are centered in the dark green area.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/pk.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/pk.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [33.68, 73.05] },
    postalCode: { format: '#####', regex: '^(\\d{5})$' },
  },
  {
    name: {
      common: 'India',
      official: 'Republic of India',
      nativeName: {
        eng: { official: 'Republic of India', common: 'India' },
        hin: { official: 'भारत गणराज्य', common: 'भारत' },
        tam: { official: 'இந்தியக் குடியரசு', common: 'இந்தியா' },
      },
    },
    tld: ['.in'],
    cca2: 'IN',
    ccn3: '356',
    cca3: 'IND',
    cioc: 'IND',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { INR: { name: 'Indian rupee', symbol: '₹' } },
    idd: { root: '+9', suffixes: ['1'] },
    capital: ['New Delhi'],
    altSpellings: [
      'IN',
      'Bhārat',
      'Republic of India',
      'Bharat Ganrajya',
      'இந்தியா',
    ],
    region: 'Asia',
    subregion: 'Southern Asia',
    languages: { eng: 'English', hin: 'Hindi', tam: 'Tamil' },
    translations: {
      ara: { official: 'جمهورية الهند', common: 'الهند' },
      bre: { official: 'Republik India', common: 'India' },
      ces: { official: 'Indická republika', common: 'Indie' },
      cym: { official: 'Republic of India', common: 'India' },
      deu: { official: 'Republik Indien', common: 'Indien' },
      est: { official: 'India Vabariik', common: 'India' },
      fin: { official: 'Intian tasavalta', common: 'Intia' },
      fra: { official: "République de l'Inde", common: 'Inde' },
      hrv: { official: 'Republika Indija', common: 'Indija' },
      hun: { official: 'Indiai Köztársaság', common: 'India' },
      ita: { official: "Repubblica dell'India", common: 'India' },
      jpn: { official: 'インド共和国', common: 'インド' },
      kor: { official: '인도 공화국', common: '인도' },
      nld: { official: 'Republiek India', common: 'India' },
      per: { official: 'جمهوری هندوستان', common: 'هند' },
      pol: { official: 'Republika Indii', common: 'Indie' },
      por: { official: 'República da Índia', common: 'Índia' },
      rus: { official: 'Республика Индия', common: 'Индия' },
      slk: { official: 'Indická republika', common: 'India' },
      spa: { official: 'República de la India', common: 'India' },
      srp: { official: 'Република Индија', common: 'Индија' },
      swe: { official: 'Republiken Indien', common: 'Indien' },
      tur: { official: 'Hindistan Cumhuriyeti', common: 'Hindistan' },
      urd: { official: 'جمہوریہ بھارت', common: 'بھارت' },
      zho: { official: '印度共和国', common: '印度' },
    },
    latlng: [20.0, 77.0],
    landlocked: false,
    borders: ['BGD', 'BTN', 'MMR', 'CHN', 'NPL', 'PAK'],
    area: 3287590.0,
    demonyms: {
      eng: { f: 'Indian', m: 'Indian' },
      fra: { f: 'Indienne', m: 'Indien' },
    },
    flag: '\uD83C\uDDEE\uD83C\uDDF3',
    maps: {
      googleMaps: 'https://goo.gl/maps/WSk3fLwG4vtPQetp7',
      openStreetMaps: 'https://www.openstreetmap.org/relation/304716',
    },
    population: 1380004385,
    gini: { '2011': 35.7 },
    fifa: 'IND',
    car: { signs: ['IND'], side: 'left' },
    timezones: ['UTC+05:30'],
    continents: ['Asia'],
    flags: {
      png: 'https://flagcdn.com/w320/in.png',
      svg: 'https://flagcdn.com/in.svg',
      alt: 'The flag of India is composed of three equal horizontal bands of saffron, white and green. A navy blue wheel with twenty-four spokes — the Ashoka Chakra — is centered in the white band.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/in.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/in.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [28.6, 77.2] },
    postalCode: { format: '######', regex: '^(\\d{6})$' },
  },
];
